name: test-release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: craig-day/compute-tag@v18
      name: compute tag
      id: compute_tag
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.ref }}
        version_scheme: continuous
        version_type: major
    - uses: ncipollo/release-action@v1
      name: create release
      with:
        tag: ${{ steps.compute_tag.outputs.next_tag }}
        name: ${{ steps.compute_tag.outputs.next_tag }}
        body: |
          This is a test
          message